import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Financial Literacy</title>
        <meta name="description" content="Generated by Financial Literacy" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://wikipedia.org">Financial Literacy!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://wikipedia.org/" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Financial Literacy.</p>
          </a>

          <a href="https://wikipedia.org/" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>
              Learn about Financial Literacy in an interactive course with
              quizzes!
            </p>
          </a>

          <a href="https://en.wikipedia.org/" className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Finance projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>{"FINANCIAL"}</h2>
            <p>Deploy your new application capable of funding!</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/vercel.svg"
              alt="NATHAN + SACHIN + DUKE"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
